### ISSUE TITLE
Translate to Russian

### ISSUE THREAD

**Issue by linonetwo** [Kenan2000/CDDA-Structured-Kenan-Modpack#201]
Do you need Kenan pack translated to Russian?

If so, I can adape my stabled translation script for you, you just need to provide 1. free API token from some translation service, for example, Yandex translation? 2. a crowdsource translate platform that you like, just like https://paratranz.cn/projects/2240

**Comment by Kenan2000** [comment]
@linonetwo Well, I thank you for this offer in advance, you're doing tremendous work translating mods from my Modpack to Chinese, I'm honestly not really interested in dealing with translations, my work is mostly tied to pure technical JSON fixing but this doesn't mean that I don't know someone who is very keen with translations along with scripts from Cataclysm Russian server who I will get in contact with hopefully, need time to contact him though, he will be really happy to use whatever scripts that automatically are able to translate mods, he is actually a mods' Russian translation project leader, he is more experienced with translations, he should be able to provide what you've listed maybe

**Comment by linonetwo** [comment]
Ok, not hurry, I also need some time to refactor my code.

I just hope this can attract more people to use this mod pack, so potentially more people will come help maintaining it.

**Comment by Kenan2000** [comment]
Closed this because no one is interested to put any effort to translate mods for this particular version of Modpack including me at all literally
