### ISSUE TITLE
PK's Rebalancing adds vitamin needs which cannot be fulfilled

### ISSUE THREAD

**Issue by Arkaile** [Kenan2000/CDDA-Structured-Kenan-Modpack#216]
PK's Rebalancing appears to add its own set of vitamin needs which cannot be fulfilled by any means other than editing one's character through the debug menu. This extra set is responsible for applying the relevant diseases, in my case they were slowed healing due to low B12 and scurvy from low vitamin C.

This is what the needs look like with PK's Rebalancing enabled.
Note the duplicates for calcium, A, B12, and C, as well as their values.
![with pk](https://user-images.githubusercontent.com/73376008/138490231-f03d7e8e-ce81-43b8-954b-39a3c5133cd3.PNG)

This is what the needs look like without the mod.
![without pk](https://user-images.githubusercontent.com/73376008/138490545-9e1c8e04-e050-4bfd-851a-c47064320af4.PNG)

The problem may be related to issue #89, but I also found a post on reddit describing exactly what I ran into, something which is apparently known to be tied to PK's Rebalancing.

https://www.reddit.com/r/cataclysmdda/comments/o6swtt/pks_rebalance_mod_is_a_great_case_study_of_why/

As is, this mod will ensure that your characters die within 3-4 months.

**Comment by Theawesomeboophis** [comment]
The vitamin things from PK are base game now, right?

**Comment by Theawesomeboophis** [comment]
Only scurvy is base game, so I have a couple of solutions I'm gonna try, fix the vitamins so the need can actually go down and isn't a perpetual spiral of deficiency (somehow), or do that and also make them new vitamins so that it's not a duplicate need.

**Comment by linonetwo** [comment]
Looking forward to a quick fix! So my character won't die.

**Comment by linonetwo** [comment]
@Theawesomeboophis Hi are you fixing this? Do you have a plan?

How to fix this problem? If you don't have time, maybe there are other people who can help!

**Comment by Arkaile** [comment]
@linonetwo 
Keep in mind the problem itself is by no means game-breaking, so it's almost certainly not a priority. The only real issue is that it breaks immersion as the only way to not die from this is to use the debug menu. The people working on this mod pack are aware of the issue and they'll likely correct it at some point, but there's no need to pester them as I'm sure there are other, more important problems they're dealing with first.

In the event you survive long enough for scurvy to start killing you, you just need to enter the debug menu, select the option to edit your character, then select "needs" to open the widow I have in the two pictures of my original post, and edit the second value for Vit C to zero. You'll be set for another couple months in-game.

**Comment by Theawesomeboophis** [comment]
I do have a plan for fixing it, I plan to attempt to make it work correctly and rename the vitamins.

**Comment by fg094** [comment]
@linonetwo reset the vitamin needs in the debug menu, wait for a little bit until the various vitamin sicknesses go away (just like wait 30 minutes in game) then once they are gone, save and quit. Then go into the PK_Rebalance mod folder and rename PK_Vitamins.json to PK_Vitamins.json.bak 
This disables the vitamin needs

**Comment by linonetwo** [comment]
Does adding new vitamins source mean we need to patch every food from game core json and other mods?
