### ISSUE TITLE
tried to put an item (mre_bag) count (1) in a container (mre_package) that cannot contain it

### ISSUE THREAD

**Issue by linonetwo** [Kenan2000/CDDA-Structured-Kenan-Modpack#239]
DEBUG    : tried to put an item (mre_bag) count (1) in a container (mre_package) that cannot contain it

 FUNCTION : ret_val<bool> item::put_in(const item &, item_pocket::pocket_type, const bool)
 FILE     : src/item.cpp
 LINE     : 1250
 VERSION  : 7b95439

**Comment by Malkeus** [comment]
Did you ever find a fix for this. I have the same error with a different set of items, would prefer an example.

**Comment by waveyl** [comment]
The volume of the contents is larger than the volume of the container, so reduce it.
See the second changed file of this commit, I cancelIed  the container of gummy vitamin as vanilla did, then the bug fixed. https://github.com/linonetwo/CDDA-Kenan-Modpack-Chinese/commit/6d186c8b55b3df07fbbc8c86cf49033c9965944f
