### ISSUE TITLE
Arcana Errors

### ISSUE THREAD

**Issue by Theawesomeboophis** [Kenan2000/CDDA-Structured-Kenan-Modpack#243]
DEBUG    : (json-error)
Json error: storage/emulated/0/Android/data/com.cleverraven.cataclysmdda.experimental/files/data/mods/Arcana/items/tool_armor.json:515:32: Invalid or misplaced field name "material" in JSON data, or value in unexpected format.

      "POWERARMOR_COMPATIBLE"
    ],
    "armor_data": { "material":
                               ^
                                [ "iron" ], "armor": [ { "encumbrance": 10, "coverage": 5, "covers": [ "torso" ] } ] },
    "armor": [ { "coverage": 40, "covers": [ "torso" ], "material": [ "iron" ], "material_thickness": 4 } ]
  },

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/android/app/jni/src/../../../../src/json.cpp
 LINE     : 125
 VERSION  : 564d632
 DEBUG    : Error: Json error: storage/emulated/0/Android/data/com.cleverraven.cataclysmdda.experimental/files/data/mods/Arcana/items/tool_armor.json:613:59: duplicate item in set defined by json array

        "coverage": 100,
        "covers": [ "torso", "arm_l", "arm_r", "leg_l", "leg_r" ],
        "material": [ "iron", "copper", "leather", "iron" ]
                                                          ^
                                                           ,
        "material_thickness": 7,
        "environmental_protection": 1

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/android/app/jni/src/../../../../src/main_menu.cpp
 LINE     : 859
 VERSION  : 564d632
These Errors appear while loading Arcana.

**Comment by chaosvolt** [comment]
Update from source repo, it's been fixed: https://github.com/chaosvolt/cdda-arcana-mod/commit/02676721a0a7d5a4e587d8aa70f37ec08251096c

**Comment by chaosvolt** [comment]
Okay, https://github.com/chaosvolt/cdda-arcana-mod/commit/0914ff46cd8e986d165936568b900b493865cec1 should fix the last few oddities I found.

**Comment by Theawesomeboophis** [comment]
Thanks.

**Comment by waveyl** [comment]
There are still some bugs, why not pull all changes from arcana repo.

**Comment by chaosvolt** [comment]
Did Kenan not properly sync the mod compilation with the source repo again?
