### ISSUE TITLE
Pk's Rebalance problem

### ISSUE THREAD

**Issue by AlexisEssen** [Kenan2000/CDDA-Structured-Kenan-Modpack#246]
Hello, i got a problem and i don't know how to fix it. The problem is:

 DEBUG    : Error: Json error: data/mods/PKs_Rebalancing/locations/doomlab.json:3343:81: y maximum is less than y minimum

      "place_items": [
        { "item": "doom_corpse", "chance": 55, "x": [ 1, 22 ], "y": [ 1, 22 ], "repeat": [ 1, 8 ] },
        { "item": "child_items", "chance": 15, "x": [ 20, 22 ], "y": [ 19, 18 ] }
                                                                                ^

      ],
      "place_fields": [ { "x": [ 20, 22 ], "y": [ 9, 14 ], "field": "fd_fatigue", "age": 2, "intensity": 2, "repeat": [ 4, 11 ] } ],

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 783
 VERSION  : 3dc1a79
^
Well, this. It shows only after new updates and only for pk, and since i took it from here, i thought that maybe you people know how to fix it? Thanks in advance for the help!
![Скриншот 07-12-2021 174755](https://user-images.githubusercontent.com/43724648/145061252-a1181860-2083-41fa-b8fa-5307fc26162d.jpg)

**Comment by AlexisEssen** [comment]
Same thing happens with Oa's more buildings or however that mod is named.

**Comment by Kenan2000** [comment]
@AlexisEssen I don't update mods that are in archived mods folder, you can fix this via changing coordinates order where you see value1>value2, switching their order to value2>value1 hopefully as well
