### ISSUE TITLE
mod errors

### ISSUE THREAD

**Issue by Milkerss** [Kenan2000/CDDA-Structured-Kenan-Modpack#250]
I downloaded the mods according to the instructions, and changed a little myself, I launch the mods with which one youtuber played, and almost all the mods do not work, version 0.F-3
![Screenshot_2022-01-04-19-08-34-411_com google android youtube](https://user-images.githubusercontent.com/97366650/148662239-43704f5e-203a-499b-af3a-931a1bc02366.jpg)

**Comment by Kenan2000** [comment]
@Milkerss I suggest you to play latest experimental versions, no motivation to work on this as well
