### ISSUE TITLE
Secronom json error

### ISSUE THREAD

**Issue by Maryionet** [Kenan2000/CDDA-Structured-Kenan-Modpack#253]
![Screenshot_2022-02-10-16-06-29-08_6fe8938556442e3d4f710ab4f9a16601](https://user-images.githubusercontent.com/68288642/153364226-aeb201be-eb47-4d23-961d-5cff001face3.jpg)

**Comment by Kenan2000** [comment]
@Maryionet Hopefully fixed in this update as well
