### ISSUE TITLE
MMA Mods Extension load error

### ISSUE THREAD

**Issue by waveyl** [Kenan2000/CDDA-Structured-Kenan-Modpack#258]
DEBUG    : style_mma_desert_wind (martialart) has two definitions from the same source (MMA_Mods_Extension)!

 FUNCTION : static void mod_tracker::check_duplicate_entries(const T&, const T&) [with T = martialart; std::enable_if_t<mod_tracker::has_src_member<T>::value>* <anonymous> = 0]
 FILE     : src/mod_tracker.h
 LINE     : 75
 VERSION  : f7c92b9

**Comment by Kenan2000** [comment]
@waveyl Hopefully fixed in this update, see if it works as well
