### ISSUE TITLE
Secronam:  t_secro_wall_flesh has roof t_secro_flat_roof_flesh, with "bash_below": false

### ISSUE THREAD

**Issue by MoonlitRiverlight** [Kenan2000/CDDA-Structured-Kenan-Modpack#265]
DEBUG    : t_secro_wall_flesh has roof t_secro_flat_roof_flesh, with "bash_below": false

 FUNCTION : virtual void ter_t::check() const
 FILE     : src/mapdata.cpp
 LINE     : 1490
 VERSION  : BN 0eaec9d

**Comment by linonetwo** [comment]
Should place in https://github.com/Kenan2000/Secronom-Zombies

**Comment by Kenan2000** [comment]
Hopefully fixed in latest update as well
