### ISSUE TITLE
Unexpected token : in JSON at position 8

### ISSUE THREAD

**Issue by linonetwo** [Kenan2000/CDDA-Structured-Kenan-Modpack#274]
Unexpected token : in JSON at position 8
/home/runner/work/CDDA-Kenan-Modpack-Chinese/CDDA-Kenan-Modpack-Chinese/Kenan-Structured-Modpack/Project_Kawaii/ammo.json

Found in auto testing https://github.com/linonetwo/CDDA-Kenan-Modpack-Chinese/runs/6735243592?check_suite_focus=true

**Comment by TpKek** [comment]
I will take a look tomorrow ( about 12 hours from now) if its not already fixed.

**Comment by Kenan2000** [comment]
@linonetwo Hopefully fixed in this update as well
