### ISSUE TITLE
Bioco issue

### ISSUE THREAD

**Issue by cjpintoy** [Kenan2000/CDDA-Structured-Kenan-Modpack#282]
DEBUG    : Error: Json error: storage/emulated/0/Android/data/com.cleverraven.cataclysmdda/files/data/mods/BioCo/monsters/monster_groups.json:5:90: missing required field "freq" in object: { "monster": "mon_BioCo_ScavBot", "weight": 85, "cost_multiplier": 0 } 

    "type": "monstergroup",
    "name": "GROUP_LAB",
    "monsters": [ { "monster": "mon_BioCo_ScavBot", "weight": 85, "cost_multiplier": 0 } ]
                                                                                         ^

  },
  {
.....for some reason its missing a field call "freq" i tried to fix it but no use

**Comment by waveyl** [comment]
Your mod is experimental version while your game is stable version.

**Comment by cjpintoy** [comment]
Oh alright thank you so much

**Comment by Kenan2000** [comment]
@cjpintoy Do not play or enable mods in Archived folder unless you have interest in fixing or maintaining them, I do not maintain them, play mods from main folder hopefully as well
