### ISSUE TITLE
mutagen_iv error

### ISSUE THREAD

**Issue by Setmaster** [Kenan2000/CDDA-Structured-Kenan-Modpack#287]
` DEBUG    : Received unrecognized iuse function mutagen_iv, using iuse::none instead

 FUNCTION : usage_from_string
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item_factory.cpp
 LINE     : 4796
 VERSION  : bf9ca7c
`

**Comment by Kenan2000** [comment]
Closing this because you've fixed it in your pull request
