### ISSUE TITLE
vamp_stuff errors

### ISSUE THREAD

**Issue by Setmaster** [Kenan2000/CDDA-Structured-Kenan-Modpack#288]
` DEBUG    : Error: crypt_map (struct itype) has two definitions from the same source (vamp_stuff)!

 FUNCTION : new_character_tab
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\main_menu.cpp
 LINE     : 947
 VERSION  : bf9ca7c

 DEBUG    : Error: t_blood_sh (struct ter_t) has two definitions from the same source (vamp_stuff)!

 FUNCTION : new_character_tab
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\main_menu.cpp
 LINE     : 947
 VERSION  : bf9ca7c

 DEBUG    : Error: Json error: data/mods/vamp_stuff/Modification_Files/Items/Armor_Set/Infused/v_bloodinfusedset.json:EOF: ers\user\Documents\Catapult\dda\game0\data\mods\vamp_stuff\Modification_Files\Items\Armor_Set\Infused\v_bloodinfusedset.json:74:4: error: FlexBuffers map has duplicate keys

 FUNCTION : new_character_tab
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\main_menu.cpp
 LINE     : 947
 VERSION  : bf9ca7c

 DEBUG    : item id canbomb is unknown (in item canbomb within HUMAN_JUNKSHOP_sell)

 FUNCTION : check_consistency
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item_group.cpp
 LINE     : 273
 VERSION  : bf9ca7c

 DEBUG    : Missing item definition: canbomb

 FUNCTION : find_template
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item_factory.cpp
 LINE     : 2364
 VERSION  : bf9ca7c

`

**Comment by Kenan2000** [comment]
Closing this because you've fixed it in your pull request
