### ISSUE TITLE
couldn't parse color: c_light_brown

### ISSUE THREAD

**Issue by Setmaster** [Kenan2000/CDDA-Structured-Kenan-Modpack#290]
` DEBUG    : couldn't parse color: c_light_brown

 FUNCTION : name_to_id
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\color.cpp
 LINE     : 109
 VERSION  : cd02b91
`

**Comment by Kenan2000** [comment]
Closing this because you've fixed this in your pull request
