### ISSUE TITLE
Two definitions from the same source 

### ISSUE THREAD

**Issue by Setmaster** [Kenan2000/CDDA-Structured-Kenan-Modpack#291]
` DEBUG    : Error: tec_secro_morph_blades_slash (class ma_technique) has two definitions from the same source (secronom_lore_expansion)!

 FUNCTION : new_character_tab
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\main_menu.cpp
 LINE     : 947
 VERSION  : 1cdaee9
`

**Comment by Kenan2000** [comment]
Closing this because you've fixed this in your pull request
