### ISSUE TITLE
Expanded Archery seems to overwrite banks' drop lists.

### ISSUE THREAD

**Issue by MoonlitRiverlight** [Kenan2000/CDDA-Structured-Kenan-Modpack#302]
Easier to notice in bank vaults, harder to notice everywhere else, but only the mod's bolters and matching ammo will spawn.

**Comment by Kenan2000** [comment]
@MoonlitRiverlight This mod is located in Archived folder, which means that this mod is abandoned, players should not play with them unless they intend to fix these mods, honestly I keep these mods there only for people to fix them themselves if they are interested for their own use for your information. What I try to work on is mods located in other folder which clearly implies this based on it's name, these mods I try to maintain hopefully as well
