### ISSUE TITLE
Invalid or misplaced field name "wheel_type" in JSON data

### ISSUE THREAD

**Issue by waveyl** [Kenan2000/CDDA-Structured-Kenan-Modpack#310]
See #65377
![image](https://github.com/Kenan2000/CDDA-Structured-Kenan-Modpack/assets/22638873/2f1d1e3e-feb8-4923-a3a4-4800c112b0c3)

**Comment by waveyl** [comment]
(World on fire)The "STAB"flag used on stinger_knife_fire is obsolete,add a "stab"value in the "melee_damage"object instead

**Comment by waveyl** [comment]
(blaze mod)Invalid or misplaced field name "standard_symbols"in JSON data
See #65721

**Comment by Kenan2000** [comment]
@waveyl Hopefully fixed in this update as well

**Comment by Kenan2000** [comment]
I have updated wheel_type format to use newer format some time ago which we can see in older commits, try to port latest updates which I have made for Blazemod hopefully
