### ISSUE TITLE
mounted_cangun (class vpart_info) has two definitions from the same source (blazemod)!

### ISSUE THREAD

**Issue by waveyl** [Kenan2000/CDDA-Structured-Kenan-Modpack#312]
![image](https://github.com/Kenan2000/CDDA-Structured-Kenan-Modpack/assets/22638873/52868efe-1b7e-4515-a55a-cc50cc8e7e05)

**Comment by waveyl** [comment]
Others:
![image](https://github.com/Kenan2000/CDDA-Structured-Kenan-Modpack/assets/22638873/aad581db-9447-4580-8838-917808ac6cca)
![image](https://github.com/Kenan2000/CDDA-Structured-Kenan-Modpack/assets/22638873/c72216be-d32d-4718-9af2-1620be82c654)
![image](https://github.com/Kenan2000/CDDA-Structured-Kenan-Modpack/assets/22638873/730f3916-99e5-40cb-be4b-26c6ac9c4402)
![image](https://github.com/Kenan2000/CDDA-Structured-Kenan-Modpack/assets/22638873/21379222-798c-47e2-a86a-be966b698a57)
![image](https://github.com/Kenan2000/CDDA-Structured-Kenan-Modpack/assets/22638873/13c48701-827b-4b0d-887e-f1539e7af1e4)

**Comment by Kenan2000** [comment]
@waveyl Hopefully fixed in this update as well
