### ISSUE TITLE
Invalid or misplaced field name "broken_symbol"in JSON data

### ISSUE THREAD

**Issue by waveyl** [Kenan2000/CDDA-Structured-Kenan-Modpack#313]
![image](https://github.com/Kenan2000/CDDA-Structured-Kenan-Modpack/assets/22638873/69c05a0c-f98e-42d6-9aa1-3f836868b070)

**Comment by waveyl** [comment]
See #65871 in DDA repo

**Comment by waveyl** [comment]
![image](https://github.com/Kenan2000/CDDA-Structured-Kenan-Modpack/assets/22638873/e0316ee8-3e32-4dc6-8389-70be83c9b606)
In blob_vehicleparts.json and blob_wheel.json

**Comment by waveyl** [comment]
![image](https://github.com/Kenan2000/CDDA-Structured-Kenan-Modpack/assets/22638873/8a4e99df-cb5a-4f79-b077-ed957449fb61)

**Comment by Kenan2000** [comment]
Hopefully fixed in this update as well
