### ISSUE TITLE
rows:row 3 column 3: '|' has no terrain, furniture,or other definition

### ISSUE THREAD

**Issue by waveyl** [Kenan2000/CDDA-Structured-Kenan-Modpack#315]
![image](https://github.com/Kenan2000/CDDA-Structured-Kenan-Modpack/assets/22638873/0258ad27-eb17-4547-b15e-8dab340ff69d)
See #66401

**Comment by waveyl** [comment]
More symbol and broken_symbol in blazemod\vehicleparts\
![image](https://github.com/Kenan2000/CDDA-Structured-Kenan-Modpack/assets/22638873/340ac4b8-ca01-443b-80fd-fa4a75e083c9)
![image](https://github.com/Kenan2000/CDDA-Structured-Kenan-Modpack/assets/22638873/148a02ed-8ef4-48ef-bdef-308dd0b014e1)

**Comment by waveyl** [comment]
![image](https://github.com/Kenan2000/CDDA-Structured-Kenan-Modpack/assets/22638873/cda1706b-1e63-4554-8a53-0c6992b89b34)
In blob_vehicleparts.json

**Comment by waveyl** [comment]
Duplicate definition
![image](https://github.com/Kenan2000/CDDA-Structured-Kenan-Modpack/assets/22638873/fb541359-fabd-4355-9e7c-cec6a01e1686)
![image](https://github.com/Kenan2000/CDDA-Structured-Kenan-Modpack/assets/22638873/10f891ab-5163-413e-91e2-abe4e8ef2b92)

**Comment by waveyl** [comment]
These are all the bugs reported when loading.

**Comment by Kenan2000** [comment]
Hopefully fixed in this update as well
