### ISSUE TITLE
Misc bugs

### ISSUE THREAD

**Issue by waveyl** [Kenan2000/CDDA-Structured-Kenan-Modpack#316]
1. Missing definition
(Dino_Mad_Science) bio_railgun, replaced in DDA#61176

2. Charges update in DDA#60885
* Charges defined but can not have any
(culinary_days_ahead) french_toast_fruity; omelette_deluxe; omelette.
(BL9) mild_curing_herb; BL9_xx_modifier; xx_curing_herb
* charges expected but not defined or <= 0
(culinary_days_ahead) soup_hotdog; soup_ketchup; eggs_glassed

3.
* tried to put an item (38_special) count (0) in a container (BL9_magnum_mk3) that cannot contain it: pocket unacceptable because item is not the correct ammo type
* tried to put an item (38_special) count (0) in a container (BL9_magnum) that cannot contain it: pocket unacceptable because item is not the correct ammo type

4.mapgen
* (Secronom) mapgen 'nested mapgen mx_secro_ssf_nested' uses invalid entry 'secro_veh_sscarrier_abandoned'; invalid vehicle group id secro_veh_sscarrier_abandoned.
They defined in Secronom_lore_expansion, so they need moved to Secronom.

* (Secronom) In nested mapgen mx_secro_ssf_nested, vehicle placement at x:[12,12], y:[10,10]: potential placement of vehicle out of bounds.  At rotation 0 the vehicle [vgroup_id ; vproto_id ] extends too far west, reaching coordinate x = -2147483636 (should be at least 0). 
In nested mapgen mx_secro_ssb_nested, vehicle placement at x:[12,12], y:[10,10]: potential placement of vehicle out of bounds.  At rotation 0 the vehicle [vgroup_id ; vproto_id ] extends too far west, reaching coordinate x = -2147483636 (should be at least 0)

**Comment by Kenan2000** [comment]
@waveyl I have fixed all of these errors except for ammo error which you mention which is error of core game itself which developers need to fix themselves honestly, some of ammo items probably are not, but most of ammo items of core game ammo types are compatible with guns in my BL9 mod hopefully
