### ISSUE TITLE
Vampiric Stuff minorly breaks Xedra Evolved

### ISSUE THREAD

**Issue by FIM43-Redeye** [Kenan2000/CDDA-Structured-Kenan-Modpack#317]
So, I play with too many mods. All the time. I also really just- mess around however I like, so if this is stupid and I'm stupid for doing it, I'm sorry, that's on me.

Vampiric Stuff changes the material of blood to human flesh, which breaks any Xedra items that contain blood as well as the Magiclysm blood fuel cell. That's the entire problem. I'm not sure why Vampiric Stuff changes the material of blood, and if there's a reason for that, that's on me- all I know is it breaks placement during world load with the simple error:

ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item.cpp:1590 [put_in] tried to put an item (blood) count (12) in a container (blood_camel) that cannot contain it: pocket unacceptable because holster does not accept this item type or form factor

I assume this shouldn't be too hard to fix. If it even matters.

**Comment by Kenan2000** [comment]
@FIM43-Redeye Hopefully fixed in this update as well
