### ISSUE TITLE
in modifier for entry within breaks_into for vpart afs_metal_rig: tried to set ammo for welder which does not have ammo or a magazine

### ISSUE THREAD

**Issue by waveyl** [Kenan2000/CDDA-Structured-Kenan-Modpack#325]
in modifier for entry within breaks_into for vpart afs_metal_rig: tried to set ammo for welder/forge/kiln/chemistry_set/hotplate/dehydrator/food_processor which does not have ammo or a magazine
See DDA#69965

**Comment by Kenan2000** [comment]
@waveyl Hopefully fixed in this update as well
