### ISSUE TITLE
Problems with Enchantments and MagicRevampAdditions

### ISSUE THREAD

**Issue by Noroji** [Kenan2000/CDDA-Structured-Kenan-Modpack#343]
The recent experimental update to use Enchantments for different stuff seems to create problems with some of the Magiclysm "Attunements" and their stat boosts.

Every Attunement that increases a stat errors out with something like this:
"Inline enchantment INLINE_ENCH_OVERCLOCKER_0 cannot be created as an enchantment already has this id."

The error also boots me back onto the main menu, removing the lines about the stat-boosting enchantments also removes the error and let's everything work as intended, without increasing your stats of course. 

[debug.log](https://github.com/Kenan2000/CDDA-Structured-Kenan-Modpack/files/14528815/debug.log)

**Comment by Kenan2000** [comment]
Yeah, I have updated files to correspond with their latest enchantments port pull request which essentially has not been merged yet so if you want to play then either revert or wait for it to be merged

**Comment by Kenan2000** [comment]
Hopefully fixed in this update as well
