### ISSUE TITLE
SAS4 mod fix:

### ISSUE THREAD

**Issue by PGR-14** [Kenan2000/CDDA-Structured-Kenan-Modpack#345]
VERY simple fix: 
replace the last block of code w/ this (Changes that last ] to ],):
  {
    "id": "mags_common",
    "type": "item_group",
    "//": "aka i got lazy doing multiple item groups",
    "copy-from": "mags_common",
    "extend": { 
    "items": [
      [ "25hvm", 100 ],
      [ "50hvm", 95 ],
      [ "75hvm", 95 ],
      [ "100hvm", 90 ],
      [ "25hvmspeedloader", 60 ],
      [ "50hvmspeedloader", 60 ],
      [ "75hvmspeedloader", 60 ],
      [ "100hvmspeedloader", 55 ],
      [ "2x50hvm", 85 ],
      [ "2x100hvm", 85 ],
      [ "180hvm", 90 ],
      [ "2x180hvm", 80 ],
      [ "10ria9mm", 95 ],
      [ "20ria9mm", 90 ],
      [ "30ria9mm", 85 ],
      [ "22ria44", 90 ],
      [ "35ria44bad", 60 ],
      [ "35ria44good", 60 ],
      [ "45ria57", 85 ],
      [ "80ria57", 85 ],
      [ "2x45ria57", 65 ],
      [ "45ria762", 90 ],
      [ "2x45ria762", 60 ],
      [ "80ria762", 85 ],
      [ "100ria762", 80 ],
      [ "2x80ria762", 90 ],
      [ "120ria762", 90 ],
      [ "5ria3006", 90 ],
      [ "8ria3006", 90 ],
      [ "12ria3006", 90 ],
      [ "15ria3006", 90 ],
      [ "20cm223", 90 ],
      [ "35cm223", 85 ],
      [ "50cm223", 80 ],
      [ "65cm223", 80 ],
      [ "100cm223", 75 ],
      [ "120cm223", 75 ],
      [ "65+15cm223", 55 ],
      [ "40cm9mm", 90 ],
      [ "60cm9mm", 80 ],
      [ "80cm9mm", 75 ],
      [ "2x40cm9mm", 60 ],
      [ "2cm12mm", 30 ],
      [ "4cm12mm", 20 ],
      [ "180cm223", 70 ],
      [ "220cm223", 65 ],
      [ "15rancor762", 60 ],
      [ "20rancor762", 50 ],
      [ "25rancor762", 40 ],
      [ "15rancor223", 60 ],
      [ "25rancor223", 50 ],
      [ "35rancor223", 40 ],
      [ "10rancor9mm", 60 ],
      [ "20rancor9mm", 50 ],
      [ "30rancor9mm", 40 ],
      [ "10ronson45", 70 ],
      [ "15ronson45", 60 ],
      [ "20ronson45", 50 ],
      [ "20ronson50", 70 ],
      [ "30ronson50", 60 ],
      [ "40ronson50", 50 ],
      [ "20ronson762", 80 ],
      [ "30ronson762", 70 ],
      [ "40ronson762", 60 ],
      [ "50ronson762", 60 ],
      [ "60ronson762", 50 ]
    ],
  }}

**Comment by Kenan2000** [comment]
@PGR-14 This mod is in Archived folder which only means that it's only kept for preservation reasons. I don't do any work on mods located in Archived folder which is true for either of my Modpacks literally. So if you want to fix it you can download it, update it to work with latest version then publish your own version of it on GitHub if you want to
