### ISSUE TITLE
missing mandatory member "bash_resist"

### ISSUE THREAD

**Issue by 327223152** [Kenan2000/CDDA-Structured-Kenan-Modpack#348]
DEBUG    : Error: Json error: data/mods/Kenan-Modpack-Chinese/Arcana/materials.json:1:2: missing mandatory member "bash_resist"

[
 ^
  {
    "type": "material",
    "id": "essencemat",

 FUNCTION : new_character_tab
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\main_menu.cpp
 LINE     : 986
 VERSION  : d6ec466

**Comment by Kenan2000** [comment]
You are likely playing stable version of Arcana on a newer game version or vice versa, this mod is not mine, neither I maintain this mod, for any questions about mods that are present in Chinese version of my Modpack but not in my Modpack like in case of Arcana mod you should address to @waveyl who maintains Chinese version which includes lots of other mods too that I am not associated with in terms of work that I try to do hopefully very well. You can, however, ask me questions about mods that are from my Modpack like Axema's Secronom along with my BL9 mod obviously but Arcana is not my mod
