### ISSUE TITLE
easy containers throws half a billion errors

### ISSUE THREAD

**Issue by Shad0wBlad321** [Kenan2000/CDDA-Structured-Kenan-Modpack#350]
easy containers on the latest experimental throws so many errors it took me 5 minutes to space through them all, most of them were about misplaced or incorrect strings I believe

**Comment by Shad0wBlad321** [comment]
i might just be stupid actually, if thats the case close this, im not going to in case this is a real issue, but i didnt realize i had to code this myself which may be the sole issue

**Comment by Kenan2000** [comment]
You do need to use script according to README to play with this mod properly essentially, it's pretty simple, made by author of this mod as conveniently as possible for other players to use said script literally
