### ISSUE TITLE
invalid attack for parrot?

### ISSUE THREAD

**Issue by Shad0wBlad321** [Kenan2000/CDDA-Structured-Kenan-Modpack#352]
DEBUG    : Error: Json error: data/mods/BL9-100%_monster_resilience_version/Monsters/BL9monsters/BL9_aliens.json:1222:23: <color_white><color_cyan>Invalid special_attacks</color>

    "special_attacks": [
      [ "PARROT", 36 ],
<color_light_red>      [ "SMASH", 10 ],</color>
                     <color_cyan>▲▲▲</color>
      [ "STRETCH_ATTACK", 10 ],
      {
</color>

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 1051
 VERSION  : cdda-experimental-2024-08-02-0201 99386ed

crashes to main menu after this

**Comment by Kenan2000** [comment]
Hopefully fixed in this update as well
