### ISSUE TITLE
make bows great again: tried to put an item (arrow_cf) count (10) in a container (quiver) that cannot contain it

### ISSUE THREAD

**Issue by Shad0wBlad321** [Kenan2000/CDDA-Structured-Kenan-Modpack#353]
DEBUG    : tried to put an item (arrow_cf) count (10) in a container (quiver) that cannot contain it: pocket unacceptable because tried to put too many charges of ammo in item

 FUNCTION : ret_val<void> item::put_in(const item&, pocket_type, bool, Character*)
 FILE     : src/item.cpp
 LINE     : 1802
 VERSION  : cdda-experimental-2024-08-02-0201 99386ed

this happens with all the arrows and quivers as far as i can tell

**Comment by Kenan2000** [comment]
Hopefully fixed in this update as well
