### ISSUE TITLE
warnings for type BL9_ammo_pouch_leg: problem with pocket: invalid ammotype 430

### ISSUE THREAD

**Issue by Shad0wBlad321** [Kenan2000/CDDA-Structured-Kenan-Modpack#354]
DEBUG    : warnings for type BL9_ammo_pouch_leg:
problem with pocket: invalid ammotype 430

 FUNCTION : void Item_factory::check_definitions() const
 FILE     : src/item_factory.cpp
 LINE     : 2512
 VERSION  : cdda-experimental-2024-08-02-0201 99386ed

and the latest experimental has a bunch of issues with monster attack types, but im not on that build so cant give proper report

**Comment by Shad0wBlad321** [comment]
i might have done something stupid actually, let me verify

**Comment by Shad0wBlad321** [comment]
nope all issues still present on latest mod and experimental version

**Comment by Kenan2000** [comment]
Hopefully fixed in this update as well
