### ISSUE TITLE
all monsters with multiple attack types (as far as i can tell) cause this message

### ISSUE THREAD

**Issue by Shad0wBlad321** [Kenan2000/CDDA-Structured-Kenan-Modpack#355]
DEBUG    : mon_BL9_supersoldier_3 specifies more than one attack of (sub)type monster_attack, ignoring all but the last.  Add different `id`s to each attack of this type to prevent this.

 FUNCTION : void mtype::add_special_attack(const JsonObject&, const std::string&)
 FILE     : src/monstergenerator.cpp
 LINE     : 1495
 VERSION  : cdda-experimental-2024-08-04-1843 1b3cce7

this also seems to be affecting miscellanious magiclysm expansions, specifically the undead mage

**Comment by Kenan2000** [comment]
Hopefully fixed in this update as well
