### ISSUE TITLE
Vampire stuff json error, invalid number format.

### ISSUE THREAD

**Issue by JohnHenryEton** [Kenan2000/CDDA-Structured-Kenan-Modpack#356]
DEBUG    : Error: Json error: H:/Games/cdda/dda/userdata/mods/vamp_stuff/Modification_Files/Locations/-Essentials/v_overmap_terrain.json:1:2: <color_white><color_cyan>In crypt1: See cost uses invalid number format</color>

<color_light_red>[</color>
<color_cyan>▲▲▲</color>
  {
    "id": "crypt1",
</color>

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 1051
 VERSION  : cdda-experimental-2024-08-07-0555 293f801

**Comment by Kenan2000** [comment]
This was fixed in latest version, just look at the files that you have specified, if you are using launcher, update mods manually or wait for launcher to pull latest updates automatically if you don't mind
