### ISSUE TITLE
issue with either magiclysm revamp or miscellaneous magiclysm causes error with looping recipe

### ISSUE THREAD

**Issue by Shad0wBlad321** [Kenan2000/CDDA-Structured-Kenan-Modpack#357]
DEBUG    : loop in comestible recipes detected: seed_mushroom -> seed_mushroom.  Such loops can be broken by either removing or altering recipes or marking one of the items involved with the NUTRIENT_OVERRIDE flag

 FUNCTION : void recipe_dictionary::find_items_on_loops()
 FILE     : src/recipe_dictionary.cpp
 LINE     : 573
 VERSION  : cdda-experimental-2024-08-08-1605 a4755e0

doesnt prevent playing, just annoying error warning

**Comment by Kenan2000** [comment]
Hopefully fixed in this update as well
