### ISSUE TITLE
BL9 missing item definition BL9_locationsmapbig

### ISSUE THREAD

**Issue by JohnHenryEton** [Kenan2000/CDDA-Structured-Kenan-Modpack#358]
DEBUG    : Missing item definition: BL9_locationsmapbig

 FUNCTION : find_template
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item_factory.cpp
 LINE     : 2559
 VERSION  : 9b2ac1a

**Comment by Kenan2000** [comment]
Update mod then make a new in-game world, ids in mod have been changed, that's why it throws this error, it's easy

**Comment by JohnHenryEton** [comment]
Ah, so this will continue with ongoing saves. Understood. Thank you.

**Comment by Kenan2000** [comment]
No problem, mate
